### ISSUE TITLE
Accuracy of solutions

### ISSUE THREAD

**Issue by thvoigtmann** [IlianPihlajamaa/ModeCouplingTheory.jl#36]
I was playing around to test for the overall accuracy of the solutions, and I noted two things that seem odd to me.

1. The splitting of integrals: in the "Fuchs" (or "moment") algorithm, one splits the convolution integral at some intermediate point, and performs integration by parts on one of them. The argument is that one shifts the derivative always to that function in the integral which is much more slowly varying, and this should be the one evaluated at later times. This suggests to split at roughly $t/2$. Thus, for integration point `it`, we'd set the splitting point to be `i2 = floor(it/2)`, and not `i2 = 2N`, as the current code does. I expect there to be a (mild) accuracy improvement when changing this.
2. The "decimation" of "moments": when the step size is shifted from $h=\delta t$ to $2h$, the mapping of the integrals over the correlators should be exact: $$\frac12\left(\frac1h\int_{(2j-1)h}^{2jh}f(t)dt+\frac1h\int_{(2j-2)h}^{(2j-1)h}f(t)dt\right)=\frac1{2h}\int_{(j-1)(2h)}^{j(2h)}f(t)dt$$ For this reason, the decimation formula should be `F_I[j]=(F_I[2j]+F_I[2j-1])/2`. However, the current code follows Flenner and Szamel and, for some part of the grid, uses `F_I[j]=(F_I[2j]+4F_I[2j-1]+F_I[2j-2])/6`, which presumably looks better, but isn't really justified given the definition of the `F_I`. I don't know how Flenner/Szamel justified their choice, but I think it actually deteriorates the accuracy of the solution.

I've created a branch https://github.com/thvoigtmann/ModeCouplingTheory.jl/tree/splitting where I've tried out the effect of the above changes. Tests are done for the F12 model, at a state point close to the glass transition for $v_2=2$. The accuracy of the solution is evaluated by Fourier-transforming both the correlator and the memory kernel, and back-inserting into the Fourier-transformed memory equation. It appears that the error in the low-frequency spectrum can be improved significantly.

I'd like to hear thoughts on why the implementation of both of the points above was chosen and whether it would not be more justified to go back to the original Fuchs implementation on those points.

**Comment by thvoigtmann** [comment]
Here are some screenshots: spectrum of the solution (blue) as a function of log frequency (plot is double-log), and error for the memory equation in yellow, for the current code:
![original](https://user-images.githubusercontent.com/67635831/213947899-91568a4b-0d0b-408c-9dc5-61ca51155729.png)
After changing the decimation scheme for the moments:
![modified](https://user-images.githubusercontent.com/67635831/213947945-2e5ae609-a82e-41a5-8d1c-20fc34da4590.png)
Note how the low-frequency part of the error goes down. This looks more dramatic than it is, but still...

Just for completeness, here's the diff between the time-domain solutions:
![Screenshot from 2023-01-23 01-13-22](https://user-images.githubusercontent.com/67635831/213948061-318fef0a-d187-49ae-8833-bc12c145958a.png)
This is "old minus new", so with the modification, the correlators decay a bit faster. The difference is rather small, which just shows that the Fourier-transform test picks up some very sensitive information.

**Comment by IlianPihlajamaa** [comment]
Thank you for spotting the bugs!
